# Generated by Django 4.0.4 on 2022-05-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sliderImage', models.ImageField(upload_to='Slider/% Y/% m/% d/')),
            ],
        ),
    ]
