# Generated by Django 4.0.4 on 2022-05-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0005_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='url',
        ),
        migrations.AddField(
            model_name='gallery',
            name='fileUpload',
            field=models.FileField(blank=True, upload_to='notices'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
