# Generated by Django 4.0.4 on 2022-05-19 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0006_remove_gallery_url_gallery_fileupload_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='Latestnews',
        ),
    ]
